//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Language()
        {
            this.Dictionaries = new HashSet<Dictionary>();
        }
    
        public int Id { get; set; }
        public string Country { get; set; }
        public string TwoLetterCountryCode { get; set; }
        public string ThreeLetterCountryCode { get; set; }
        public string Language1 { get; set; }
        public string TwoLetterLangCode { get; set; }
        public string ThreeLetterLangCode { get; set; }
        public string CultureInfoCode { get; set; }
        public bool IsDefault { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dictionary> Dictionaries { get; set; }
    }
}
