//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class R1
    {
        public string Task { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string University { get; set; }
        public string State { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public int InvoiceId { get; set; }
        public int TeamId { get; set; }
        public bool IsFirstTeam { get; set; }
        public decimal TeamUnitCost { get; set; }
        public string TypeOfRegistration { get; set; }
        public decimal FirstTeamFee { get; set; }
        public System.DateTime DueDate { get; set; }
        public decimal ExtraTeamDiscount { get; set; }
        public int ExtraParticipantCount { get; set; }
        public decimal ExtraParticipantUnitCost { get; set; }
        public decimal ExtraParticipantAmount { get; set; }
        public decimal Expr1 { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> ConventionalFee { get; set; }
    }
}
