//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyResultDetail
    {
        public int Id { get; set; }
        public int SurveyResultId { get; set; }
        public int QuestionAnswerId { get; set; }
        public string Value { get; set; }
        public string Comment { get; set; }
    
        public virtual SurveyResult SurveyResult { get; set; }
    }
}
