//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamSafetyItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeamSafetyItem()
        {
            this.TeamSafetyItemLogs = new HashSet<TeamSafetyItemLog>();
        }
    
        public int Id { get; set; }
        public int TeamId { get; set; }
        public int SafetyItemId { get; set; }
        public string LastContent { get; set; }
        public string LastComment { get; set; }
        public Nullable<int> ItemStatus { get; set; }
        public string AttachedFileUrl { get; set; }
    
        public virtual SafetyItem SafetyItem { get; set; }
        public virtual Team Team { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamSafetyItemLog> TeamSafetyItemLogs { get; set; }
    }
}
