//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamMember
    {
        public int Id { get; set; }
        public Nullable<int> TeamId { get; set; }
        public string MemberUserId { get; set; }
        public Nullable<bool> RegistrationStatus { get; set; }
        public Nullable<bool> Survey { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Team Team { get; set; }
    }
}
