//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamGradeDetail
    {
        public int Id { get; set; }
        public string JudgeUserId { get; set; }
        public int TeamId { get; set; }
        public int GradeDetailId { get; set; }
        public Nullable<double> Point { get; set; }
        public string Description { get; set; }
        public string Signature { get; set; }
    
        public virtual GradeDetail GradeDetail { get; set; }
        public virtual Team Team { get; set; }
    }
}
