//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamSafetyItemDetailLog
    {
        public int Id { get; set; }
        public int TeamSafetyItemDetailId { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Value { get; set; }
        public string Comment { get; set; }
    
        public virtual TeamSafetyItemDetail TeamSafetyItemDetail { get; set; }
    }
}
