//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewSurveyResult
    {
        public string Email { get; set; }
        public string UserName { get; set; }
        public string PhoneNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string University { get; set; }
        public string TeamName { get; set; }
        public Nullable<int> TaskId { get; set; }
        public string TaskName { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string UserId { get; set; }
        public string Value { get; set; }
        public Nullable<int> TeamId { get; set; }
        public int QuestionAnswerId { get; set; }
        public int Id { get; set; }
        public string Comment { get; set; }
    }
}
