//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTeam
    {
        public int Id { get; set; }
        public int TaskId { get; set; }
        public string Name { get; set; }
        public string Task { get; set; }
        public Nullable<bool> Survey { get; set; }
        public string MemberName { get; set; }
        public string Identifier { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public string RoleName { get; set; }
        public string RoleId { get; set; }
        public string UserDefiner { get; set; }
        public Nullable<System.DateTime> LastSignIn { get; set; }
        public Nullable<int> UniversityId { get; set; }
        public string University { get; set; }
        public string StreetLine1 { get; set; }
        public string StreetLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string ShortBio { get; set; }
        public string ProfilePictureUrl { get; set; }
        public string ResumeUrl { get; set; }
        public string MemberUserId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> TeamState { get; set; }
        public string TeamImageUrl { get; set; }
        public bool EmailConfirmed { get; set; }
        public bool LockoutEnabled { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public Nullable<bool> RegistrationStatus { get; set; }
        public Nullable<int> SizeId { get; set; }
        public string T_Shirt_Size { get; set; }
        public string EmgyPersonFirstName { get; set; }
        public string EmgyPersonLastName { get; set; }
        public string EmgyPersonPhoneNumber { get; set; }
        public string EmgyPersonRelationship { get; set; }
        public string PhoneNumber { get; set; }
        public string LabResultUrl { get; set; }
        public string WrittenReportUrl { get; set; }
        public Nullable<int> TeamNumber { get; set; }
        public Nullable<int> JacketSizeId { get; set; }
        public string JacketSize { get; set; }
        public Nullable<int> DietTypeId { get; set; }
        public string DietType { get; set; }
        public string UniversityPictureUrl { get; set; }
        public string TaskDescription { get; set; }
        public bool PayStatus { get; set; }
        public bool Deactivate { get; set; }
        public Nullable<bool> SubmitStatus { get; set; }
        public Nullable<System.DateTime> WrittenReportDate { get; set; }
        public bool SuppressScoring { get; set; }
    }
}
